#!/bin/bash
echo "The result is $(echo "obase=bestchol $(echo "ibase=water $WATER" | tr "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ" "0123456789abcdefghijklmnopqrstuvwxyz") + $(echo "ibase=stir $STIR" | tr "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ" "0123456789abcdefghijklmnopqrstuvwxyz")" | tr "0123456789abcdefghijklmnopqrstuvwxyz" "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ")"
