#!/bin/bash
echo "The result is $(echo "ibase=water $WATER + ibase=stir $STIR" | tr "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ" "0123456789abcdefghijklmnopqrstuvwxyz" | tr "0123456789abcdefghijklmnopqrstuvwxyz" "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ")"
